### PR TITLE
use jniloader instead of bundled code

### PR DESCRIPTION
**Pull request by fommil**
use common logic for loading your natives (code inspired by the cibuddy code, but greatly improved for a larger variety of scenarios)

### CODE REVIEW

**Comment by fommil** [comment]
any interest in this?

**Comment by fommil** [comment]
@cibuddy @mirkojahn is this PR doomed to failure?

Incidentally, almost a year later, the jniloader is being used by a lot of people - primarily through `netlib-java` and has proven itself in corporate environments.

**Comment by mirkojahn** [comment]
Hi Sam,

sorry for the totally outdated reply, but somehow I didn't see the request
notification. I'll take a look at it tomorrow night. Again sorry for the
late reply and thanks for your contribution!

Cheers,
Mirko

**Comment by fommil** [comment]
no problem, I do it myself :-)

**Comment by mirkojahn** [comment]
Hi Sam,

first of all, many thanks for your contribution! You're code is fact more elegant and robust than what I have. The code was actually taken (as stated in the documentation and license files) from the codeminders project. The only reason I have this class in place was based on your request in the past and a "pseudo" unit test to verify that accessing HID devices should work. Now I am not sure what way to proceed basically, because I do not want to depend on a LGPLv3 library as a full maven dependency when I don't (and can't) use it. CIBuddy is running in OSGi, which has its own native library loading mechanism. The way I see it, there are 3 options and I'd like to hear you're opinion on it.
1. **Extracting the static loading in a separate Maven module** that depends on the HID driver and consumes its binaries (without the need to be OSGi compliant). By that I do not have to include the static loading code and the driver is freed from the LGPL license dependency. Everyone is happy. The only downside is that the module would basically contain only one class and one test. The test would then test capabilities useful (successful loading) of another module (the one carrying the driver).
2. **Getting rid of the ClassPathLibraryLoader** and only expose the list of binaries in an Interface. In the test code use your jniloader with the list of libraries to run the tests. Change the jniloader dependencies to test scope. Drawback, one has to know about your library (or look into the test code) to be able to use the bundles binaries in plain java and it is an API break, but besides that I think it is the cleanest  one - not much boiler plate, straight to the task and easy to reproduce.
3. Never change a running system/ remove the static handling of the binaries entirely. Worst case in my opinion. No really an option - I like progress ;-)

Last but not least, I agree with your comment that the exception should be propagated and not hidden behind a return statement. When touching the code, I would prefer to change that behaviour.

So, what do you think? My favorite is number two, because I do not have none OSGi use cases on my roadmap, but I might be missing something, especially regarding your usage. For a transition phase, the "old" usage could be deprecated and the new one propagated, so that nothing is breaking for now.

Cheers,
Mirko

**Comment by fommil** [comment]
I don't see what the fuss about LGPL is. Libusb is LGPL. It's easily the best license for middleware. 

Option 1 sounds best. You could turn the current artefact into a parent and then create a native and core module your below that.

**Comment by fommil** [comment]
I'm sanitising my repo list and it looks like this PR has been zombied.

**Pull request closed without merging**
